name: Build Docker Image CI

on:
  push:
    branches: [ "mainnoway" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag invmgrweb:$(date +%s)

    - name: Run the Docker container
      run: |
          echo "completed"
